on: [push]

jobs:
  slack_upload_job:
    runs-on: ubuntu-latest
    name: Upload test file
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: echo "Test file 1" > test.txt
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@6b9d825872e4d91a7337fe13eaea4516c1dfff56
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: test.txt
          channel: random
